development:
  adapter: postgresql
  encoding: unicode
  database: ijiel_development
  host: localhost
  pool: 5
  port: 5432
  username: nlu
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: ijiel_test
  host: localhost
  pool: 5
  port: 5432
  username: nlu
  password: 